#pragma once
//
// Created by Matt Zapp on 4/3/2018.
//


#include <array>
#include <cstdint>
#include <meta/audio/Asymp.h>
#include <meta/dsp/BandlimitedOsc.h>
#include "../inc/er1_dsp/Waveshapes.h"


namespace meta::ER1
{
    /**
     * This class defines a band-limited wavetable oscillator that is used for
     * many of basic virtual analog synthesis functions in the ER-1.
     *
     * It offers the 2 audio-rate and 2 of the modulation-rate waveforms
     * originally supported by the ER-1: Sine, Triangle, Saw, and Square.
     * Analysis of the audio-rate waveforms indicates that the Triangle and
     * Sine functions are actually generated by integrating a band-limited Square
     * signal, and thus the Triangle is not a clean shape, and the Sine includes
     * some additional odd harmonics in keeping with the original.
     */

    using BaseOsc = BandLimitedOsc<16, 128, 12>;
    using Shapes = SimpleWaveShapeFunc<>;

    class Oscillator
        : public BaseOsc
    {
    public:
        using BaseOsc::BandLimitedOsc;
        WaveShape shape;
    private:
        float wave_shape(float accumulator_state) override;
    };
}

